export const FitnessAchievementAbi = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "string", name: "achievementCode", type: "string" },
      { indexed: false, internalType: "uint256", name: "reward", type: "uint256" },
    ],
    name: "AchievementClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "string", name: "exerciseType", type: "string" },
      { indexed: false, internalType: "uint256", name: "steps", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "calories", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "durationMinutes", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "WorkoutLogged",
    type: "event",
  },
  {
    inputs: [{ internalType: "string", name: "achievementCode", type: "string" }],
    name: "claimAchievement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "achievementCode", type: "string" }],
    name: "getRewardForAchievement",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getRewardBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserAchievements",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserStats",
    outputs: [
      { internalType: "uint256", name: "totalWorkouts", type: "uint256" },
      { internalType: "uint256", name: "totalSteps", type: "uint256" },
      { internalType: "uint256", name: "totalCalories", type: "uint256" },
      { internalType: "uint256", name: "totalDurationMinutes", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getWorkoutCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getWorkouts",
    outputs: [
      {
        components: [
          { internalType: "string", name: "exerciseType", type: "string" },
          { internalType: "uint256", name: "steps", type: "uint256" },
          { internalType: "uint256", name: "calories", type: "uint256" },
          { internalType: "uint256", name: "durationMinutes", type: "uint256" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
        ],
        internalType: "struct FitnessAchievement.Workout[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "string", name: "achievementCode", type: "string" },
    ],
    name: "hasAchievement",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "string", name: "achievementCode", type: "string" },
    ],
    name: "isEligibleForAchievement",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "exerciseType", type: "string" },
      { internalType: "uint256", name: "steps", type: "uint256" },
      { internalType: "uint256", name: "calories", type: "uint256" },
      { internalType: "uint256", name: "durationMinutes", type: "uint256" },
    ],
    name: "logWorkout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
